# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 31383043949e2344e7e27b5b7dab8b84d825d86f4d97534a6c35d208b1a3be34608cfa9819894d37ed5b2cfeac681306c6688f8c1781c142f91db34f620d5a0c

test:
  secret_key_base: 648411c6bfd393590e97bfa68a1445118664da9155e8188ac6e37c3f43d4a478e35f2f657568fb0287748a661bd984ec319a1b7447765214989018d97ce2afad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
